from fastapi import APIRouter, Depends, HTTPException, Query, status
from fastapi.responses import StreamingResponse
from sqlalchemy.orm import Session
from typing import Optional, List
import io

from app.core.database import get_db
from app.api.auth import get_current_user
from app.models.user import User
from app.schemas.rer_schema import (
    CommitBatchRequest,
    EvolutionReportResponse,
    HistoryItem
)
from app.services.rer_service import RERService

router = APIRouter(prefix="/rer", tags=["Codebase Pulse"])

@router.post("/analyze", status_code=status.HTTP_200_OK)
async def analyze_commits(
    payload: CommitBatchRequest,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """Receive processed commit information from n8n and store it."""
    if not payload.commits:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Commits list cannot be empty."
        )
    
    stored = RERService.store_commits(db, current_user.id, payload.commits)
    return {
        "status": "success",
        "message": f"Successfully processed and stored {len(stored)} commits.",
        "processed_count": len(stored)
    }

@router.get("/report", response_model=EvolutionReportResponse)
async def get_evolution_report(
    repository: str = Query(..., description="Repository name, e.g. owner/repo"),
    branch: str = Query("main", description="Branch name"),
    week: Optional[str] = Query(None, description="ISO Week, format: YYYY-Www"),
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """Retrieve the computed Repository Evolution Report (RER) for a specific week."""
    report = RERService.get_evolution_report(db, repository, branch, week)
    if not report:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="No commits found for the specified repository and branch."
        )
    return report

@router.get("/history", response_model=List[HistoryItem])
async def get_evolution_history(
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """Retrieve evolution report history for the authenticated user."""
    return RERService.get_history(db, current_user.id)

@router.get("/download")
async def download_evolution_report(
    repository: str = Query(..., description="Repository name"),
    branch: str = Query("main", description="Branch name"),
    week: Optional[str] = Query(None, description="ISO Week, format: YYYY-Www"),
    format: str = Query("markdown", description="Format to download: markdown, pdf, docx"),
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """Generate and download a Repository Evolution Report (RER)."""
    report = RERService.get_evolution_report(db, repository, branch, week)
    if not report:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="No evolution data found to download."
        )

    # Format the report text
    buf = io.BytesIO()
    title = f"Repository Evolution Report (RER) - {report['repository']} ({report['week']})"
    
    doc_text = f"""======================================================================
{title.upper()}
======================================================================
Generated by DevOracle AI Codebase Pulse
Date: {report['recent_activity'][0].commit_date.strftime('%Y-%m-%d') if report['recent_activity'] else 'N/A'}
Branch: {report['branch']}
======================================================================

1. EXECUTIVE SUMMARY
--------------------
- Repository: {report['repository']}
- Week Number: {report['week']}
- Total Commits: {report['total_commits']}
- Files Changed: {report['files_changed_count']}
- Contributors: {', '.join(report['contributors']) if report['contributors'] else 'None'}

2. HIGH-ACTIVITY AREAS (TOP DIRECTORIES)
----------------------------------------
"""
    for area in report['high_activity_areas']:
        doc_text += f"- {area.directory}: {area.commits_count} commits, {area.files_count} files modified\n"
        
    doc_text += "\n3. REPEATEDLY MODIFIED FILES\n----------------------------\n"
    for f in report['repeatedly_modified_files']:
        doc_text += f"- {f.file_path}: modified {f.change_count} times (+{f.additions}/-{f.deletions})\n"

    doc_text += "\n4. DAILY TIMELINE & COMMITS\n---------------------------\n"
    for day, items in report['daily_timeline'].items():
        doc_text += f"\n--- {day.upper()} ({len(items)} commits) ---\n"
        for item in items:
            doc_text += f"[{item.commit_sha[:8]}] by {item.author}: {item.commit_message.strip()} (+{item.additions}/-{item.deletions})\n"

    buf.write(doc_text.encode("utf-8"))
    buf.seek(0)

    filename = f"RER_{repository.replace('/', '_')}_{report['week']}.{format}"
    
    media_type = "text/markdown" if format == "markdown" else "application/octet-stream"
    headers = {"Content-Disposition": f"attachment; filename={filename}"}
    return StreamingResponse(buf, media_type=media_type, headers=headers)
